### ISSUE TITLE
only positive results

### ISSUE THREAD

**Issue by wellenc** [obheda12/GitDorker#12]
It would be cool if there were a function --results whitch outputs in terminal/file only the + results instead of # and -

**Comment by obheda12** [comment]
Thank you that's definitely good feedback. The "-" results serve to let you know you are in some capacity hitting rate limits. Also you can output to a file of raw results using the "-o" switch

**Comment by obheda12** [comment]
The "-o" switch is the "--results" switch in this case.

For further information please refer to the detailed documentation here:

tinyurl.com/gitdorker

**Comment by obheda12** [comment]
Closing this as this is intended functionality :)
