### ISSUE TITLE
error occurred: https://docs.github.com/rest

### ISSUE THREAD

**Issue by noobsdt** [obheda12/GitDorker#13]
When I use single token (```-t <token>```) it works fine but ```-tf <token_file>``` returns ```error occurred: https://docs.github.com/rest```

![gitdorkerissue](https://user-images.githubusercontent.com/28983163/96296616-13d85380-0fdf-11eb-9107-b7208037101c.png)

**Comment by obheda12** [comment]
Please make sure your tokens are separated by a new line. 

For example:

token1
token2
token3

**Comment by obheda12** [comment]
let me know if this fixed the issue and I will close this.

**Comment by ConorDSherman** [comment]
@obheda12 I can confirm that my tokens are in the correct position but I am getting this error. I have created 2 person access tokens for this project to search my private repos in my org's github account. FWIW I am an I admin I can manually dork just fine. When I check the tokens I see that the Personal Access token is "never used"

Separate can you please confirm what permissions (least privilege) do you need specifically for that Personal Access Token?

**Comment by uBadRequest** [comment]
I think this happens when the token is invalid, skip to next token maybe?

**Comment by obheda12** [comment]
In addition try to configure the token to have all permissions enabled. @noobsdt please let me know if you're still having issues, otherwise i will be closing this.

**Comment by noobsdt** [comment]
@obheda12 sorry for the late reply. Actually, my GitHub token was deleted. Now it's working perfectly.
