### ISSUE TITLE
Facing Rate limiting issue 

### ISSUE THREAD

**Issue by HackSunil007** [obheda12/GitDorker#15]
<img width="1440" alt="Screenshot 2020-10-18 at 11 30 05 AM" src="https://user-images.githubusercontent.com/41774691/96359888-5744d600-1135-11eb-91b2-359d4fc2ab95.png">

**Comment by obheda12** [comment]
This has already been covered in Issue #2

**Comment by obheda12** [comment]
please reference this issue and let me know if you need any additional clarification

**Comment by HackSunil007** [comment]
Thanks @obheda12 issue is resolved :)
