### ISSUE TITLE
Rate Limit triggered while execute the command

### ISSUE THREAD

**Issue by cryptoknife** [obheda12/GitDorker#19]
When we execute the query the rate limit gets triggered. Can we increase the delay for the first iteration of queries.
![gitdorker](https://user-images.githubusercontent.com/52606335/102005742-57321280-3d41-11eb-97d6-97930a28101a.png)

**Comment by obheda12** [comment]
Increase the number of personal access tokens. You are only using my one token and it is getting rate limited too quickly.

**Comment by cryptoknife** [comment]
Sure I will add some more access tokens. Thank you for the advice.
