### ISSUE TITLE
error occurred: https://docs.github.com/v3/search/

### ISSUE THREAD

**Issue by xaeroborg** [obheda12/GitDorker#2]
Hello Omar, I am getting this error when I run the following command `python3 /home/GitDorker/GitDorker.py -tf /home/git_token.txt -org target -d /home/GitDorker/Dorks/alldorks.txt -o gitdorks_target.txt`

![gitdorker_error](https://user-images.githubusercontent.com/33274680/95534052-74292d00-0a02-11eb-9fb4-7a43d5b3bc0d.png)

**Comment by 0xth** [comment]
Same issue

**Comment by 0xth** [comment]
error occurred: https://docs.github.com/rest

**Comment by obheda12** [comment]
check the alldorks file. Are there any blank lines? also change "target" to an actual company name.

**Comment by xaeroborg** [comment]
Actually I used the actual target name instead of "target" but the command syntax is the same, anyways I made it work. @0xth  try this `python3 /home/GitDorker/GitDorker.py -tf /home/git_token.txt -q target.com -d /home/GitDorker/Dorks/alldorks.txt -o gitdorks_target.txt`

@obheda12 your tool works amazing, its the command syntax in the blog that is making such error

**Comment by obheda12** [comment]
what did you put for the "-org " field inititally? GitHub has a different system for organizations. You can't input a domain in "-org" but you can with "-q" as you did in your above command.

Hope that clears up any confusion and glad you like it :)

**Comment by obheda12** [comment]
just to clear up any confusion: say I want to search on tesla's github organization. Tesla on github is not "tesla" rather it is "teslamotors". Therefore the following command would be as such:

python3 GitDorker.py -tf *tokensfile* -org teslamotors -d *dorksfile*

If i wanted to search on tesla's domain, "tesla.com", then I will specify the command as you did @xaeroborg. However please note that searching on a domain vs within an organization's account will yield different results.

**Comment by obheda12** [comment]
If there are no further concerns I will be closing this issue.

**Comment by xaeroborg** [comment]
> 
> 
> just to clear up any confusion: say I want to search on tesla's github organization. Tesla on github is not "tesla" rather it is "teslamotors". Therefore the following command would be as such:
> 
> python3 GitDorker.py -tf _tokensfile_ -org teslamotors -d _dorksfile_
> 
> If i wanted to search on tesla's domain, "tesla.com", then I will specify the command as you did @xaeroborg. However please note that searching on a domain vs within an organization's account will yield different results.

Thanks for the tip/suggestion @obheda12

**Comment by xaeroborg** [comment]
> 
> 
> If there are no further concerns I will be closing this issue.

Yes you may close the issue.

**Comment by xaeroborg** [comment]
> 
> 
> what did you put for the "-org " field inititally? GitHub has a different system for organizations. You can't input a domain in "-org" but you can with "-q" as you did in your above command.

Anyways your explanation [above](https://github.com/obheda12/GitDorker/issues/2#issuecomment-706384505) has cleared everything. 
> 
> Hope that clears up any confusion and glad you like it :)

for the -org I used "target" instead of "target.com" for example `-org google`

**Comment by obheda12** [comment]
Glad to hear it, happy hunting! Keep me updated if you guys get any bounties! 

For now I'm closing this issue

**Comment by 1522402210** [comment]
the same error

[-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
[-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
[-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
[-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
[-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
[-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
[-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
[-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
[-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
[-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
[-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
[-] error occurred: https://developer.github.com/v3/#abuse-rate-limits

**Comment by yassineaboukir** [comment]
> the same error
> 
> [-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
> [-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
> [-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
> [-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
> [-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
> [-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
> [-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
> [-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
> [-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
> [-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
> [-] error occurred: https://developer.github.com/v3/#abuse-rate-limits
> [-] error occurred: https://developer.github.com/v3/#abuse-rate-limits

As mentioned above:

- `-org` argument should be used for the organization's Github username, not domain name (e.g: -org teslamotors)
- `-q` argument should be used for a targeted domain name (e.g: -q teslamotors.com)
- Try to generate and use at least 4 Github API tokens to avoid getting rate limited.

**Comment by obheda12** [comment]
Per yassines response, please incorporate additional tokens so GitDorker may rotate between them. You have been rate limited as GitHub only allows 30 requests every minute per account.

In order to circumvent this you May use multiple tokens form unique accounts in the token file and change the sleep function from sleeping every 30 requests to the number of requests enabled by having multiple tokens. For example 3 unique tokens from 3 unique accounts would enable you to have 90 requests per minute.

**Comment by obheda12** [comment]
I will be closing this if there are no further comments

**Comment by daddyhack** [comment]
> error occurred: https://docs.github.com/rest

i am also getting this error. have added multiple tokens.

**Comment by yassineaboukir** [comment]
Perhaps try to run it without mutithreading.

> > error occurred: https://docs.github.com/rest
> 
> i am also getting this error. have added multiple tokens.

Perhaps try to run it without mutithreading.

**Comment by obheda12** [comment]
Please note that utilizing personal access tokens from the **same** account will NOT increase the rate limit. Rate limits in github are tied to unique accounts. You must use personal access tokens from multiple unique accounts should you like to bypass the 30 request per minute limit.

Regarding @yassineaboukir comment, he is correct. The multithreading can sparse out the tokens. I will revisit this functionality in the future to better it. For now please try to keep threads to one if you are experiencing rate limits.

**Comment by obheda12** [comment]
Closing this issue as additional comments are becoming redundant

**Comment by monustark** [comment]
error occurred: https://docs.github.com/v3/search/ In Progress $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  0/241

problem
