### ISSUE TITLE
Use GitDorcker for Specified Repository  

### ISSUE THREAD

**Issue by Deku-izuku-dotcom** [obheda12/GitDorker#21]
Hello 

Thanks for the amazing Tool 

I wonder if i can , Launch it on Only one Repository , not the entire Organisation ?? 

Best regards

**Comment by obheda12** [comment]
You can using the query tag and github advanced search syntax specifying the "repo" tag in your query

**Comment by Deku-izuku-dotcom** [comment]
Thanks a  lot 
it Work for me :  repo:owner/name
Reference :https://docs.github.com/en/github/searching-for-information-on-github/searching-for-repositories
