### ISSUE TITLE
Empty CSV

### ISSUE THREAD

**Issue by AHewitt** [obheda12/GitDorker#24]
Problem: Every time I run gitdorker I get a 0 byte CSV file

- I am running the latest version of GitDorker and python 3.8.5
- I am using this command:

python3 GitDorker.py -tf example_tf -org example_org -d alldorksv3 -output example_out

but example_out.csv is always empty, despite seeing lots of results in the console output

**Comment by obheda12** [comment]
My apologies, there was a bug in the output of the most recent version. Please pull the latest version and lmk if you still have the same issue

**Comment by AHewitt** [comment]
Yep it's working now, thank you!
