### ISSUE TITLE
[-] error occurred: https://docs.github.com/rest

### ISSUE THREAD

**Issue by git-user321** [obheda12/GitDorker#25]
i am using 5 tokens from 2 different accounts
command i tried-
python3 GitDorker.py -tf /root/git_tokens.txt -org orgname -d /root/alldorksv3 -o githubdorks.txt 
also error same with "-u mygithubaccount"
weird thing is with -t single_token both above options works fine
![gitdork1](https://user-images.githubusercontent.com/32525182/106768916-70c94980-6662-11eb-8114-3cb0ec4fafd3.png)
 but quite slow.
please help i want to use -tf option somehow.

**Comment by obheda12** [comment]
check the org you are searching and if it is a valid GitHub org, no queries are being generated so i suspect that the org you are specifying does not exist or you have a typo

**Comment by git-user321** [comment]
i checked it with org its fine. with -t one token it works fine. only encounter error with -tf. I tried with -u option as well same results. with -tf it doesn't work with -t it works. strange

**Comment by obheda12** [comment]
please see if your tokenfile has an empty line, space, or any characters that were inputted incorrectly invalidating the token

**Comment by shahriarr-sec** [comment]
I am having the same issue.

**Comment by git-user321** [comment]
> please see if your tokenfile has an empty line, space, or any characters that were inputted incorrectly invalidating the token

really tried it carefully but still same error i will add video of same later, anyway right now using single token only.

**Comment by shahriarr-sec** [comment]
> > please see if your tokenfile has an empty line, space, or any characters that were inputted incorrectly invalidating the token
> 
> really tried it carefully but still same error i will add video of same later, anyway right now using single token only.



> > please see if your tokenfile has an empty line, space, or any characters that were inputted incorrectly invalidating the token
> 
> really tried it carefully but still same error i will add video of same later, anyway right now using single token only.

Hello I am having this error even with a single token.I am sure I have no problem in token bcz I used the same token with guthub-dork by techgaun and it worked just fine.I dont know what's the issue here.Can I have your commands for sungle token??

**Comment by obheda12** [comment]
-t <TOKEN>

**Comment by shahriarr-sec** [comment]
This time it worked just fine with two tokens. I used two different token from two diff account and gave them all the permissions.

My Command:
python3 GitDorker.py -tf tf/TOKENSFILE -q name -d Dorks/100dorks -o output

cat tf/TOKENSFILE
token1
token2

output was in a good csv format.

Thank you ,obheda12 for this amazing tool.

**Comment by obheda12** [comment]
No problem glad it worked out for you!

**Comment by Broly157** [comment]
Hey @obheda12 

I have got same problem, i don't think this is how gitDorker Works ?
![image](https://user-images.githubusercontent.com/34275803/108959669-bc3baa00-769a-11eb-8a98-290c040c8644.png)
i have done pip3 install -r requirements.txt
then ran `python3 GitDorker.py -tf TOKEN (with no space's / 2 token on new lines)  -org target (which has a org in github for sure) -d Dorks/alldorksv3`
Where am i doing wrong?
Hope to hear from you
Thanks

**Comment by obheda12** [comment]
one of your tokens is not valid anymore. GitHub most likely flagged the account with that token and it is no longer able to be in use
