### ISSUE TITLE
Main command error due to case sensitive folder name

### ISSUE THREAD

**Issue by Shrimant12** [obheda12/GitDorker#28]
To run the GitDorker script, author has given sample command on the main page. https://github.com/obheda12/GitDorker

The command is `python3 GitDorker.py -tf TOKENSFILE -q tesla.com -d dorks/DORKFILE -o tesla`

If user runs this command as it is, it will give error because the dorks folder in main directory is named as **Dorks** and in command its written as **dorks**

Please make **D** capital in command OR rename the folder from **Dorks** to **dorks**

**Comment by obheda12** [comment]
Thansk for the heads up!
