### ISSUE TITLE
-k keyword not working

### ISSUE THREAD

**Issue by gprime31** [obheda12/GitDorker#29]
am I missing something with the keyword? (-k) tried from dork file results and it finds nothing:
python3 GitDorker.py -tf tf/TOKENSFILE -q tesla.com -k filename:sshd_config -o tesla
python3 GitDorker.py -tf tf/TOKENSFILE -q tesla.com -k language:yaml -o tesla
python3 GitDorker.py -tf tf/TOKENSFILE -q tesla.com -k "pwd" -o tesla
python3 GitDorker.py -tf tf/TOKENSFILE -q tesla.com -k "slack_api" -o tesla
python3 GitDorker.py -tf tf/TOKENSFILE -q tesla.com -k "private_key" -o tesla

with and without quotes and alot of combos. 
any ideas?
just want to search a single term/keyword.

**Comment by obheda12** [comment]
hi this is an issue im working on atm, i may remove the k flag altogether as it's a bit redundant and allow single dorks but in the meantime you can replace it with the '-d' flag and specify a single word in a file. thanks for bringing this up

**Comment by gprime31** [comment]
thanks 
it would be handy for just one search though.
but the single word in a file is good for me.
keep up the great work!!! program is awesome!!!
