### ISSUE TITLE
Variable error

### ISSUE THREAD

**Issue by vivekperkawar** [obheda12/GitDorker#30]
File "GitDorker.py", line 404, in <module>
sys.stdout.write(colored('%s' % new_url, 'white'))
NameError: name 'new_url' is not defined

![1619524959883](https://user-images.githubusercontent.com/64719666/116238209-b76ca280-a77e-11eb-94c7-7fcd0c5f7163.jpg)

I am on latest version and this issue still exist. plz consider fixing it!

**Comment by obheda12** [comment]
This is not an issue with gitdorker, rather it is an issue with the dorks being provided. Please ensure that the dorks are free from any blank lines.

**Comment by surajxkadam** [comment]
I'm using your dorks still getting the same above error.
`python3 GitDorker.py -tf github_tokens.txt -e 10 -q tesla.com -p -ri -d Dorks/alldorksv3`
