### ISSUE TITLE
Provide a Dockerfile?

### ISSUE THREAD

**Issue by jdbohrman** [obheda12/GitDorker#6]
It would be really nice to have the ability to run this via Docker with the ability to just pass in the env variables. Would this be something you'd like to see contributed?

**Comment by obheda12** [comment]
That's a good point and I would, my only concern would be should it create any performance issues. Thoughts?

**Comment by menum724** [comment]
Like power in the battery..... I see these new Duracell Optimum now. Sounds
cool. But really don't want to take up too much of your time. I see there's
raw code by CI/CB platform. Or repositories in and on Github. Now I do
subscribe to this thread.

**Comment by obheda12** [comment]
Sorry menum im not sure I follow?

**Comment by tommy-muehle** [comment]
Hi,

I'm currently using this Dockerfile successfully (and without noticeable performance decreases):

```Dockerfile
FROM python:3.8-slim

COPY requirements.txt .
RUN pip install --user -r requirements.txt

WORKDIR /code

COPY ./GitDorker.py .
ENTRYPOINT [ "python", "GitDorker.py" ]
```

via

```sh
$ docker build -t gitdorker:latest .
```
and

```sh
$ docker run --rm -v $PWD:/code gitdorker:latest -h
```

One note, I had to change the requirements file to this:

```txt
termcolor
tqdm
requests
```

@obheda12 
Let me know if you're interested in a PR for this.

**Comment by obheda12** [comment]
Hi tommy, thank you I would be please go ahead and I will accept it after reviewing

**Comment by obheda12** [comment]
The docker file has been provided

**Comment by menum724** [comment]
Thanks Re: I am
