### ISSUE TITLE
Error with itertools

### ISSUE THREAD

**Issue by CyberBeta** [obheda12/GitDorker#7]
When try to install the requirements. got this error message.
ERROR: Could not find a version that satisfies the requirement itertools (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for itertools (from -r requirements.txt (line 1))

**Comment by obheda12** [comment]
can you try running GitDorker and without itertools. I'd like to see the error if possible

**Comment by obheda12** [comment]
I believe python's standard library already includes itertools so you should be able to run it actually. If you can run it successfully please let me know and I'll update the requirements file as necessary

**Comment by nagarjun007** [comment]
Hi,

i'm having same issue not able to install itertools. output is blank when i run without itertools. any suggestions?

OS: windows 10
python version:3.8.5

![image](https://user-images.githubusercontent.com/33154218/96210813-5a529180-0f90-11eb-8a46-354ef32b9173.png)

**Comment by obheda12** [comment]
place the following in a text file and run "pip3 install -r textfile"
argparse	
requests	
csv	
termcolor
colored
tqdm
Unidecode	
lockfile	
keyboard
Unidecode	
lockfile	
keyboard

I'm not sure exactly which requirement it is but I believe you may be missing one.

**Comment by nagarjun007** [comment]
still facing same issue :( . i'm getting similar error for CSV also

may i know which OS and version of python are you using? i'll try in a similar setup

![image](https://user-images.githubusercontent.com/33154218/96237541-0d37e500-0fbb-11eb-94b9-9875383921fe.png)

**Comment by obheda12** [comment]
Yes Im running Kali Linux 2020.2 and Python 3.8

**Comment by nagarjun007** [comment]
Hi @obheda12 ,

finally found the issue. in windows, we need to execute command like this and it worked

gitdorkery.py -h

earlier i was trying python3 gitdorker.py -h

Thanks for your support.

![image](https://user-images.githubusercontent.com/33154218/96327560-44a89f00-1058-11eb-889b-2f38a14181b8.png)

**Comment by obheda12** [comment]
Ah I see. Glad you figured it out! Closing this now :)
